Resources:
  csvUploader:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: csv-uploader
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::660191058507:role/LabRole
      Code:
        ZipFile: |
          import boto3
          import csv
          import pymysql

          def lambda_handler(event, context):
              s3 = boto3.resource('s3')
              bucket_name = 'my-new-bucket-fvsfdvbfdbvdfbdf'
              key = 'Housing.csv'
              s3.Bucket(bucket_name).download_file(key, '/tmp/my-file')

              rds = pymysql.connect(
                  host='database-clase-3.cdzuiytok7rw.us-east-1.rds.amazonaws.com',
                  user='admin',
                  password='56431643',
                  database='database-clase-3'
              )

              with open('/tmp/my-file', 'r') as file:
                  csv_data = csv.reader(file)

                  # Create a cursor object to interact with the database
                  cursor = rds.cursor()

                  # Skip the header row
                  next(csv_data)

                  # Insert data into the MySQL table
                  for row in csv_data:
                      # Adjust column names as per your CSV structure and table schema
                      query = "INSERT INTO database-clase-3 (date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
                      values = (row[0], row[1], row[2], row[3], row[4], row[5], row[6], row[7], row[8], row[9], row[10], row[11], row[12], row[13], row[14], row[15], row[16], row[17])
                      cursor.execute(query, values)

                  # Commit the changes to the database
                  rds.commit()

                  # Close the cursor and database connection
                  cursor.close()
                  rds.close()

              return 'CSV file imported successfully'
      Runtime: python3.10
